ICD_train_file: '/your_path/RAD/csv_files/2025-02-22-ICD53-dis-train.csv'
ICD_test_file: '/your_path/RAD/csv_files/2025-02-22-ICD53-dis-test.csv'

image_res: 512
batch_size: 64
test_batch_size: 64
grad_accumulation_steps: 2
num_workers: 8
test_num_workers: 8
temp: 0.07
mlm_probability: 0.15
queue_size: 8192
momentum: 0.995
alpha: 0.4

optimizer: {opt: adamw, lr: 0.0001, weight_decay: 0.01}
schedular: {sched: cosine, lr: 0.00005, epochs: 15, min_lr: 0.000001, decay_rate: 1, warmup_lr: 0.000001, warmup_epochs: 15, cooldown_epochs: 0}